language: java
jdk:
    - openjdk8

cache:
    directories:
	- "$HOME/.cache"

jobs:
    - stage: deploy
      name: 'Deploy to Sandbox Environment"
      script:
      - mvn clean install
      - cp .travis.settings.xml $HOME/.m2/settings.xml
      - mvn clean install deploy -DmuleDeploy -Dserver=$server -Dworkers=$workers -DworkerType=$workerType -Denvironment=$environment -DmuleVersion=$muleVersion -DappName=$applicationName
      if: branch = sandbox